# Generated by Django 5.2.12 on 2026-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Software, Cloud Computing', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.CharField(blank=True, help_text='Comma separated (e.g., Python, Django, AWS)', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
