# Generated by Django 5.2.12 on 2026-03-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_worker_type_alter_job_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(blank=True, help_text='e.g., +91 9876543210', max_length=15, null=True),
        ),
    ]
