# Generated by Django 5.2.8 on 2026-06-13 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_repost_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topicgroup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('design', 'Design'), ('business', 'Business'), ('career', 'Career'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
