# Generated by Django 5.2.12 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='core_skills',
            field=models.TextField(blank=True, help_text='e.g., Python, Django, Cloud Architecture', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True, help_text='e.g., B.S. in Computer Science', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, help_text='e.g., Cybersecurity, Open Source Development', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g., Software Engineer', max_length=150),
        ),
    ]
