# Generated by Django 5.2.12 on 2026-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_core_skills_customuser_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner_image',
            field=models.ImageField(blank=True, default='banners/default_banner.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to your GitHub profile', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='open_to_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_website',
            field=models.URLField(blank=True, help_text='Link to your personal site', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
